import sgMail from '@sendgrid/mail';

// Initialize SendGrid with provided API key
// NOTE: API key must be provided via environment variable (SENDGRID_API_KEY)
// Never hard-code real SendGrid keys in source control.
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;

if (SENDGRID_API_KEY && SENDGRID_API_KEY !== 'placeholder') {
  try {
    sgMail.setApiKey(SENDGRID_API_KEY);
    console.log('✅ SendGrid client initialized successfully');
  } catch (error) {
    console.log('⚠️  SendGrid client initialization failed:', error.message);
  }
} else {
  console.log('⚠️  SendGrid API key not configured - Email features will be disabled');
}

/**
 * Send email alert using SendGrid
 * @param {Object} alert - Alert configuration
 * @param {number} currentValue - Current sensor value
 * @param {string} deviceId - Device ID
 * @returns {Promise<boolean>} Success status
 */
export async function sendEmailAlert(alert, currentValue, deviceId) {
  try {
    if (!SENDGRID_API_KEY || SENDGRID_API_KEY === 'placeholder') {
      console.log('📧 SendGrid API key not configured, logging email content instead');
      logEmailContent(alert, currentValue, deviceId);
      return true;
    }

    const emailContent = {
      to: alert.value,
      from: process.env.SENDGRID_FROM_EMAIL || 'alerts@smartagro.com',
      subject: `🚨 Farm Alert: ${getParameterLabel(alert.parameter)} ${alert.comparison} ${alert.threshold}`,
      html: generateEmailHTML(alert, currentValue, deviceId),
      text: generateEmailText(alert, currentValue, deviceId)
    };

    console.log('📧 Sending email alert to:', alert.value);
    const response = await sgMail.send(emailContent);
    
    console.log('✅ Email sent successfully:', response[0].statusCode);
    return true;
  } catch (error) {
    console.error('❌ Error sending email alert:', error);
    
    // Log the email content for debugging
    logEmailContent(alert, currentValue, deviceId);
    return false;
  }
}

/**
 * Generate HTML email content
 */
function generateEmailHTML(alert, currentValue, deviceId) {
  const isCritical = alert.critical;
  const criticalClass = isCritical ? 'background-color: #fee2e2; border-left: 4px solid #dc2626;' : 'background-color: #fef3c7; border-left: 4px solid #d97706;';
  const criticalText = isCritical ? 'CRITICAL ALERT' : 'Regular Alert';
  const criticalColor = isCritical ? '#dc2626' : '#d97706';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Farm Alert Notification</title>
    </head>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="${criticalClass} padding: 20px; margin-bottom: 20px; border-radius: 8px;">
        <h1 style="margin: 0 0 10px 0; color: ${criticalColor}; font-size: 24px;">
          ${isCritical ? '🚨' : '🔔'} ${criticalText}
        </h1>
        <p style="margin: 0; font-size: 16px; font-weight: bold;">
          Smart Agriculture Monitoring System
        </p>
      </div>

      <div style="background-color: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
        <h2 style="margin-top: 0; color: #374151;">Alert Details</h2>
        
        <div style="margin-bottom: 15px;">
          <strong>Parameter:</strong> ${getParameterLabel(alert.parameter)}
        </div>
        
        <div style="margin-bottom: 15px;">
          <strong>Condition:</strong> ${getComparisonLabel(alert.comparison)} ${alert.threshold}
        </div>
        
        <div style="margin-bottom: 15px;">
          <strong>Current Value:</strong> 
          <span style="color: ${criticalColor}; font-weight: bold; font-size: 18px;">
            ${currentValue}
          </span>
        </div>
        
        <div style="margin-bottom: 15px;">
          <strong>Device ID:</strong> ${deviceId}
        </div>
        
        <div style="margin-bottom: 15px;">
          <strong>Alert Type:</strong> ${alert.type.toUpperCase()}
        </div>
        
        <div>
          <strong>Time:</strong> ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Colombo' })}
        </div>
      </div>

      <div style="background-color: #e5f3ff; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
        <h3 style="margin-top: 0; color: #1e40af;">Recommended Actions</h3>
        <ul style="margin: 0; padding-left: 20px;">
          ${generateRecommendations(alert.parameter, currentValue, alert.threshold)}
        </ul>
      </div>

      <div style="text-align: center; padding: 20px; background-color: #f3f4f6; border-radius: 8px;">
        <p style="margin: 0; color: #6b7280; font-size: 14px;">
          This alert was generated by your Smart Agriculture Monitoring System.<br>
          Please check your dashboard for more details and take appropriate action.
        </p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate plain text email content
 */
function generateEmailText(alert, currentValue, deviceId) {
  const criticalText = alert.critical ? 'CRITICAL ALERT' : 'Regular Alert';
  
  return `
${alert.critical ? '🚨' : '🔔'} ${criticalText} - Smart Agriculture Monitoring System

Alert Details:
- Parameter: ${getParameterLabel(alert.parameter)}
- Condition: ${getComparisonLabel(alert.comparison)} ${alert.threshold}
- Current Value: ${currentValue}
- Device ID: ${deviceId}
- Alert Type: ${alert.type.toUpperCase()}
- Time: ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Colombo' })}

Recommended Actions:
${generateTextRecommendations(alert.parameter, currentValue, alert.threshold)}

This alert was generated by your Smart Agriculture Monitoring System.
Please check your dashboard for more details and take appropriate action.
  `.trim();
}

/**
 * Log email content when SendGrid is not configured
 */
function logEmailContent(alert, currentValue, deviceId) {
  const emailContent = {
    to: alert.value,
    subject: `🚨 Farm Alert: ${getParameterLabel(alert.parameter)} ${alert.comparison} ${alert.threshold}`,
    body: generateEmailText(alert, currentValue, deviceId)
  };
  
  console.log('📧 Email content (SendGrid not configured):', emailContent);
}

/**
 * Generate recommendations based on parameter and value
 */
function generateRecommendations(parameter, currentValue, threshold) {
  const recommendations = [];
  
  switch (parameter) {
    case 'soilMoisturePct':
      if (currentValue < threshold) {
        recommendations.push('Check irrigation system and water supply');
        recommendations.push('Consider increasing watering frequency');
        recommendations.push('Monitor soil moisture levels closely');
      } else {
        recommendations.push('Check for overwatering or drainage issues');
        recommendations.push('Reduce irrigation frequency if needed');
      }
      break;
      
    case 'soilTemperature':
    case 'airTemperature':
      if (currentValue > threshold) {
        recommendations.push('Check for heat stress in plants');
        recommendations.push('Consider shading or cooling measures');
        recommendations.push('Monitor plant health closely');
      } else {
        recommendations.push('Check for cold stress in plants');
        recommendations.push('Consider heating or protection measures');
      }
      break;
      
    case 'airHumidity':
      if (currentValue > threshold) {
        recommendations.push('Check for fungal disease risk');
        recommendations.push('Improve air circulation');
        recommendations.push('Consider dehumidification');
      } else {
        recommendations.push('Check for plant dehydration');
        recommendations.push('Consider increasing humidity');
      }
      break;
      
    case 'airQualityIndex':
    case 'co2':
    case 'nh3':
      if (currentValue > threshold) {
        recommendations.push('Check ventilation system');
        recommendations.push('Investigate source of contamination');
        recommendations.push('Consider air purification');
      }
      break;
      
    default:
      recommendations.push('Check device and sensor functionality');
      recommendations.push('Review monitoring system settings');
  }
  
  return recommendations.map(rec => `<li>${rec}</li>`).join('');
}

/**
 * Generate text recommendations
 */
function generateTextRecommendations(parameter, currentValue, threshold) {
  const recommendations = [];
  
  switch (parameter) {
    case 'soilMoisturePct':
      if (currentValue < threshold) {
        recommendations.push('- Check irrigation system and water supply');
        recommendations.push('- Consider increasing watering frequency');
        recommendations.push('- Monitor soil moisture levels closely');
      } else {
        recommendations.push('- Check for overwatering or drainage issues');
        recommendations.push('- Reduce irrigation frequency if needed');
      }
      break;
      
    case 'soilTemperature':
    case 'airTemperature':
      if (currentValue > threshold) {
        recommendations.push('- Check for heat stress in plants');
        recommendations.push('- Consider shading or cooling measures');
        recommendations.push('- Monitor plant health closely');
      } else {
        recommendations.push('- Check for cold stress in plants');
        recommendations.push('- Consider heating or protection measures');
      }
      break;
      
    case 'airHumidity':
      if (currentValue > threshold) {
        recommendations.push('- Check for fungal disease risk');
        recommendations.push('- Improve air circulation');
        recommendations.push('- Consider dehumidification');
      } else {
        recommendations.push('- Check for plant dehydration');
        recommendations.push('- Consider increasing humidity');
      }
      break;
      
    case 'airQualityIndex':
    case 'co2':
    case 'nh3':
      if (currentValue > threshold) {
        recommendations.push('- Check ventilation system');
        recommendations.push('- Investigate source of contamination');
        recommendations.push('- Consider air purification');
      }
      break;
      
    default:
      recommendations.push('- Check device and sensor functionality');
      recommendations.push('- Review monitoring system settings');
  }
  
  return recommendations.join('\n');
}

/**
 * Get parameter label
 */
function getParameterLabel(parameter) {
  const labels = {
    soilMoisturePct: 'Soil Moisture (%)',
    soilTemperature: 'Soil Temperature (°C)',
    airTemperature: 'Air Temperature (°C)',
    airHumidity: 'Air Humidity (%)',
    airQualityIndex: 'Air Quality Index',
    co2: 'CO2 Level (ppm)',
    nh3: 'NH3 Level (ppm)'
  };
  return labels[parameter] || parameter;
}

/**
 * Get comparison label
 */
function getComparisonLabel(comparison) {
  const labels = {
    '>': 'Greater than',
    '<': 'Less than',
    '>=': 'Greater than or equal to',
    '<=': 'Less than or equal to'
  };
  return labels[comparison] || comparison;
}
